export const UPDATE_COCKTAILS = "UPDATE_COCKTAILS";
export const CLEAR_COCKTAILS = "CLEAR_COCKTAILS";
export const TOGGLE_LOADING_ON = "TOGGLE_LOADING_ON";
export const TOGGLE_LOADING_OFF = "TOGGLE_LOADING_OFF";
