export const UPDATE_DRINK = "UPDATE_DRINK";
export const UPDATE_NEXT_DRINK = "UPDATE_NEXT_DRINK";
export const UPDATE_PREV_DRINK = "UPDATE_PREV_DRINK";
export const SHOW_DRINK_INFO = "SHOW_DRINK_INFO";
export const HIDE_DRINK_INFO = "HIDE_DRINK_INFO";
